import prisma from './prisma';

const movies = [
  {
    code: 'MOV-0001',
    title: 'Thanh Gươm Diệt Quỷ: Vô Hạn Thành',
    description: 'Trận chiến cuối cùng giữa Sát Quỷ Đội và Muzan Kibutsuji diễn ra bên trong Vô Hạn Thành – pháo đài không gian do Thượng Huyền điều khiển. Các Trụ Cột và Tanjiro bước vào cuộc chiến sinh tử quyết định số phận nhân loại.',
    studio: 'Ufotable',
    director: 'Haruo Sotozaki',
    cast: ['Natsuki Hanae', 'Akari Kito', 'Yoshitsugu Matsuoka', 'Hiro Shimono', 'Takahiro Sakurai', 'Toshihiko Seki'],
    categories: ['Hoạt hình', 'Hành động', 'Phiêu lưu'],
    slug: 'thanh-guom-diet-quy-vo-han-thanh',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2024-08-31'),
    duration: 120,
    language: ['Tiếng Nhật'],
    subtitles: ['Tiếng Anh', 'Tiếng Việt'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/vi/b/bb/%C3%81p_ph%C3%ADch_Thanh_g%C6%B0%C6%A1m_di%E1%BB%87t_qu%E1%BB%B7-_V%C3%B4_h%E1%BA%A1n_th%C3%A0nh.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=BSkUboiyeCo',
    videoUrl: 'https://www.youtube.com/watch?v=2kWgaYv7D2w&list=RD2kWgaYv7D2w&start_radio=1&t=436s',
    tags: ['anime', 'demon-slayer', 'kimetsu-no-yaiba', 'hanh-dong', 'fantasy', 'nhat-ban'],
  },
  {
    code: 'MOV-0002',
    title: 'Pokémon The Movie: Sức Mạnh Của Chúng Ta',
    description: 'Tại thành phố Fula, nơi tổ chức lễ hội Gió thường niên để tôn vinh Pokémon huyền thoại Lugia, Satoshi và Pikachu gặp gỡ nhiều con người với những hoàn cảnh khác nhau. Khi một mối đe dọa bất ngờ xuất hiện và phá vỡ sự cân bằng của thiên nhiên, tất cả phải cùng nhau hợp sức để bảo vệ thành phố và chứng minh rằng sức mạnh thật sự đến từ sự đoàn kết.',
    studio: 'OLM, Inc.',
    director: 'Tetsuo Yajima',
    cast: ['Rica Matsumoto', 'Ikue Otani', 'Megumi Hayashibara', 'Inuko Inuyama'],
    categories: ['Hành động', 'Phiêu lưu', 'Gia đình'],
    slug: 'httpsss-imagessaostarvnwwebp700201811013975151image004jpg',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2026-02-13'),
    duration: 100,
    language: ['Tiếng Hàn'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://ss-images.saostar.vn/wwebp700/2018/11/01/3975151/image004.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=ILKiX297L3A',
    videoUrl: 'https://www.youtube.com/watch?v=ILKiX297L3A',
    tags: ['pokemon', 'phieu-luu', 'anime', 'gia-dinh', 'hoat-hinh'],
  },
  {
    code: 'MOV-0003',
    title: 'Lật Mặt 7: Một Điều Ước',
    description: 'Phần 7 series Lật Mặt - câu chuyện cảm động về tình cảm gia đình và ước mơ.',
    studio: 'Lý Hải Production',
    director: 'Lý Hải',
    cast: ['Trấn Thành', 'Lý Hải', 'Ốc Thanh Vân'],
    categories: ['Gia đình', 'Tình cảm'],
    slug: 'lat-mat-7-mot-dieu-uoc',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2024-04-26'),
    duration: 132,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR7-_fZaMkOU9rBjPhlQweTIDzOksGqHlFeVwuaVKtSaQsY8hsK',
    trailerUrl: 'https://www.youtube.com/watch?v=QdtPQ0wV53M',
    videoUrl: 'https://www.youtube.com/watch?v=QdtPQ0wV53M',
    tags: ['phim-viet', 'gia-dinh', 'lat-mat'],
  },
  {
    code: 'MOV-0004',
    title: 'Mai',
    description: 'Câu chuyện tình cảm sâu sắc về cô gái massage tên Mai và cuộc gặp gỡ định mệnh.',
    studio: 'Trấn Thành Town',
    director: 'Trấn Thành',
    cast: ['Phương Anh Đào', 'Tuấn Trần', 'Trấn Thành'],
    categories: ['Tình cảm', 'Tâm lý'],
    slug: 'mai',
    status: 'published',
    ageRating: 'T16',
    releaseDate: new Date('2024-02-10'),
    duration: 131,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/vi/3/36/Mai_2024_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=EX6clvId19s',
    videoUrl: 'https://www.youtube.com/watch?v=EX6clvId19s',
    tags: ['phim-viet', 'tinh-cam', 'tran-thanh'],
  },
  {
    code: 'MOV-0005',
    title: 'Đào, Phở và Piano',
    description: 'Bộ phim tái hiện Hà Nội trong những ngày đầu kháng chiến chống Pháp mùa đông 1946.',
    studio: 'Bộ VH-TT-DL',
    director: 'Phi Tiến Sơn',
    cast: ['Doãn Quốc Đam', 'Cao Thùy Linh'],
    categories: ['Chiến tranh', 'Lịch sử', 'Tình cảm'],
    slug: '',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2024-02-12'),
    duration: 96,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/vi/2/29/%C3%81p_ph%C3%ADch_%C4%90%C3%A0o%2C_ph%E1%BB%9F_v%C3%A0_piano.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=qn1t_biQigc',
    videoUrl: 'https://www.youtube.com/watch?v=7GHTMU6UfcY',
    tags: ['phim-viet', 'lich-su', 'chien-tranh'],
  },
  {
    code: 'MOV-0006',
    title: 'Nắng',
    description: 'Nắng kể câu chuyện cảm động về hai mẹ con Mưa và bé Nắng sống nương tựa vào nhau. Người mẹ có phần ngây ngô nhưng đầy tình thương dành cho con. Biến cố xảy ra khi bé Nắng bị đưa về thành phố, buộc người mẹ phải vượt qua mọi khó khăn để tìm lại con mình. Bộ phim mang đến nhiều tiếng cười xen lẫn nước mắt về tình mẫu tử thiêng liêng.',
    studio: 'Galaxy Studio',
    director: 'Đồng Đăng Giao',
    cast: ['Thu Trang', 'Kim Thư', 'Tiến Luật', 'Hoài Linh'],
    categories: ['Tâm lý', 'Gia đình', 'Hài'],
    slug: 'nang',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2016-10-06'),
    duration: 115,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://cdn.galaxycine.vn/media/n/a/nang_2.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=lg-z-vF4T18',
    videoUrl: 'https://www.youtube.com/watch?v=cZPW0j4v_6A&t=5315s',
    tags: ['phim-viet', 'gia-dinh', 'hai', 'cam-dong ', 'viet-nam'],
  },
  {
    code: 'MOV-0007',
    title: 'Báu Vật Trời Cho',
    description: 'Báu Vật Trời Cho sẽ ra mắt vào Tết 2026',
    studio: 'Bluebells Studios',
    director: 'Lê Thanh Sơn',
    cast: ['Tuấn Trần, Phương Anh Đào', 'Quách Ngọc Ngoan', 'Võ Tấn Phát', 'Khương Lê'],
    categories: ['Tình cảm', 'Gia đình', 'Chính kịch'],
    slug: 'bau-vat-troi-cho',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2026-02-16'),
    duration: 124,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/vi/6/64/Bau_vat_troi_cho.jpg',
    trailerUrl: 'https://youtu.be/YPvmab5K0LQ',
    videoUrl: 'https://youtu.be/YPvmab5K0LQ',
    tags: ['phim-viet', 'tet-2026', 'bau-vat-troi-cho'],
  },
  {
    code: 'MOV-0008',
    title: 'Nhà Bà Nữ',
    description: 'Phim hài gia đình kể về cuộc sống hỗn loạn trong một gia đình Việt Nam nhiều thế hệ.',
    studio: 'Trấn Thành Town',
    director: 'Trấn Thành',
    cast: ['Trấn Thành', 'Lê Giang', 'NSƯT Ngọc Giàu'],
    categories: ['Hài', 'Gia đình'],
    slug: 'nha-ba-nu',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2023-01-28'),
    duration: 128,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://www.imdb.com/title/tt26427249/mediaviewer/rm3057791489/?ref_=tt_ov_i',
    trailerUrl: 'https://youtu.be/IkaP0KJWTsQ?si=s8JIMScycnGwYmqC',
    videoUrl: 'https://youtu.be/xa4dTn5znb4?si=FjaXP4JIQzd3uwmd',
    tags: ['phim-viet', 'hai', 'gia-dinh'],
  },
  {
    code: 'MOV-0009',
    title: 'Hai Muối',
    description: 'Bộ phim tài liệu nghệ thuật khám phá cuộc sống của ngư dân làm muối ven biển miền Trung.',
    studio: 'CGV',
    director: 'Trịnh Đình Lê Minh',
    cast: ['Hoàng Yến Chibi', 'Lạc Hoàng Long'],
    categories: ['Tâm lý', 'Tình cảm'],
    slug: 'hai-muoi',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2023-11-17'),
    duration: 95,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://vtcpay.vn/blog/wp-content/uploads/2024/09/hai-muoi-phim.jpeg',
    trailerUrl: 'https://www.youtube.com/watch?v=fvUgLfVrPeI',
    videoUrl: 'https://www.youtube.com/watch?v=fvUgLfVrPeI',
    tags: ['phim-viet', 'tam-ly'],
  },
  {
    code: 'MOV-0010',
    title: 'Thanh Sói',
    description: 'Phim hành động Việt Nam về nữ sát thủ trẻ tuổi và thế giới ngầm đầy nguy hiểm.',
    studio: 'Studio68',
    director: 'Ngô Thanh Vân',
    cast: ['Đồng Ánh Quỳnh', 'Ngô Thanh Vân'],
    categories: ['Hành động', 'Tội phạm'],
    slug: 'thanh-soi',
    status: 'published',
    ageRating: 'T18',
    releaseDate: new Date('2022-12-30'),
    duration: 105,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://bazaarvietnam.vn/wp-content/uploads/2022/12/HBVN-phim-thanh-soi-ngo-thanh-van-e1671762537716.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=scRyC2Gkito',
    videoUrl: 'https://www.youtube.com/watch?v=scRyC2Gkito',
    tags: ['phim-viet', 'hanh-dong'],
  },
  {
    code: 'MOV-0011',
    title: 'Tuyển Thủ Dê: Mùi Vị Chiến Thắng',
    description: 'Will - một chú dê nhỏ với ước mơ trở thành tuyển thủ bóng roarbll chuyên nghiệp. Dù bị xem thường vì vóc dáng nhỏ bé, cậu cùng đồng đội vượt qua định kiến, thi đấu bùng nổ và truyền cảm hứng rằng ai cũng có thể tỏa sáng.',
    studio: 'GOAT Studios',
    director: 'Tyree Dillihay',
    cast: ['Will Arnett', 'Gabriel Iglesias', 'Stephen Curry', 'Keke Palmer'],
    categories: ['Hài', 'Hoạt hình', 'Gia đình'],
    slug: 'tuyen-thu-de-mui-vi-chien-thang',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2024-03-25'),
    duration: 93,
    language: ['Tiếng Anh'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://image.tmdb.org/t/p/w500/wZRJ3Q2XRJHov1SS80sTXbfjkz9.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=Pjul1QfzBIM',
    videoUrl: 'https://www.youtube.com/watch?v=Pjul1QfzBIM',
    tags: ['goat', 'animation', 'sports', 'family', 'comedy'],
  },
  {
    code: 'MOV-0012',
    title: 'Inside Out 2',
    description: 'Riley bước vào tuổi thiếu niên với những cảm xúc mới: Lo Lắng, Ghen Tị, Chán Nản, Xấu Hổ.',
    studio: 'Pixar',
    director: 'Kelsey Mann',
    cast: ['Amy Poehler', 'Maya Hawke'],
    categories: ['Hoạt hình', 'Gia đình', 'Hài'],
    slug: 'inside-out-2',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2024-06-14'),
    duration: 96,
    language: ['Tiếng Anh'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/1/0/1080x1350-insideout.jpg',
    trailerUrl: 'https://youtu.be/VWavstJydZU?si=USCC9QNzMzBFRtXi',
    videoUrl: 'https://youtu.be/LEjhY15eCx0?si=jVyy1lMVJ8kKp6CJ',
    tags: ['hoat-hinh', 'pixar', 'gia-dinh'],
  },
  {
    code: 'MOV-0013',
    title: 'Lạc Phàm Trần: Hậu Duệ Chức Nữ',
    description: 'Tham luyến trần gian thì đã sao? Tình cảm chính là phép thuật của người phàm, ngay cả thần tiên cũng khó tránh khỏi kiếp nạn. Chức Nữ vì tự ý rời bỏ nhiệm vụ mà sa vào trần thế, bị tinh tú phản phệ, liên lụy đến Ngưu Lang và các con. Nhiều năm sau, Kim Phong, hậu nhân của Chức Nữ bị đưa đến Thần giới, quyết trở lại nhân gian để chuộc tội cho mẹ và thu hồi tinh tú. Trên hành trình, cậu tình cờ gặp Tiểu Phàm (Ngọc Lộ), một cô gái khát khao lên Thần giới tìm mẹ. Cả hai cùng đồng hành trong cuộc phiêu lưu thu hồi tinh tú, nhưng cũng từ đó, vô tình khám phá ra chân tướng tội lỗi năm xưa của Chức Nữ…',
    studio: 'Light Chaser Animation Studios',
    director: 'Zhong Ding',
    cast: ['Ryan Reynolds', 'Hugh Jackman'],
    categories: ['Hoạt hình', 'Phiêu lưu'],
    slug: 'lac-pham-tran-hau-due-chuc-nu',
    status: 'published',
    ageRating: 'T18',
    releaseDate: new Date('2024-07-25'),
    duration: 118,
    language: ['Tiếng Trung'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://cinema.momocdn.net/img/30047600552782627-lacphamtran.png?size=M',
    trailerUrl: 'https://youtu.be/qGdqYTJAJfM',
    videoUrl: 'https://youtu.be/qGdqYTJAJfM',
    tags: ['animation', 'fantasy', 'mythology'],
  },
  {
    code: 'MOV-0014',
    title: 'Chuột Nhí Siêu Tốc Độ',
    description: 'Edda, một cô chuột trẻ đầy tham vọng, có cơ hội tham gia giải đua xe lớn nhất châu Âu khi cải trang thành tay đua thần tượng của mình. Trên đường đua đầy thử thách, Edda phải vượt qua những âm mưu phá hoại và chứng minh rằng kích thước nhỏ bé không ngăn cản được ước mơ lớn.',
    studio: 'Viva Kids',
    director: 'Waldemar Fast',
    cast: ['Gemma Arterton', 'Thomas Brodie-Sangster', 'Hayley Atwell'],
    categories: ['Hài', 'Phiêu lưu', 'Hoạt hình'],
    slug: 'chuot-nhi-sieu-toc-do',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2026-02-25'),
    duration: 96,
    language: ['Tiếng Anh'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://cinema.momocdn.net/img/149993016019706191-mousse.png?size=M',
    trailerUrl: 'https://youtu.be/OVxEYaN1vzw',
    videoUrl: 'https://youtu.be/OVxEYaN1vzw',
    tags: ['animation', 'racing', 'family', 'advanture'],
  },
  {
    code: 'MOV-0015',
    title: 'Mùi Phở',
    description: 'Câu chuyện về sự xung đột thế hệ và những va chạm giữa quan niệm cũ và lối sống hiện đại, xoay quanh món Phở - biểu tượng ẩm thực Việt. Đằng sau những mâu thuẫn và tranh cãi ấy, từng bí mật dần được hé lộ, mở ra hành trình tìm lại sự ấm áp của tình thân qua những tình tiết hài hước, dí dỏm và đầy duyên dáng.',
    studio: 'Beta Studio',
    director: 'Minh Beta',
    cast: ['NSƯT Hồng Vân', 'Kiều Minh Tuấn', 'Kaity Nguyễn', 'Lê Dương Bảo Lâm'],
    categories: ['Hài', 'Gia đình'],
    slug: 'mui-pho',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2026-02-25'),
    duration: 106,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://cinema.momocdn.net/img/33061769328054253-mpfinal.png?size=M',
    trailerUrl: 'https://youtu.be/PfLNuXyLA4Q',
    videoUrl: 'https://youtu.be/PfLNuXyLA4Q',
    tags: ['tet', 'gia dinh', 'am thuc', 'vietnam'],
  },
  {
    code: 'MOV-0016',
    title: 'Tiểu Yêu Quái Núi Lãng Lãng',
    description: 'Giữa thế đạo mà "kẻ mạnh làm vua", một nhóm tiểu yêu quái vô danh gồm Heo, Ếch, Chồn và Khỉ Đột vốn chỉ quen bị bắt nạt và xua đuổi, đã quyết tâm hợp lực thay đổi số phận. Chúng quyết định thực hiện một phen đánh cược điên rồ khi giả danh đoàn thỉnh kinh, vượt vạn dặm tới Tây Thiên để cầu xin Phật Tổ sự bất tử và vang danh. Hành trình hài hước và đầy tính nhân văn đã chinh phục trái tim người xem.',
    studio: 'Shengshi Studio',
    director: 'Yu Shui',
    cast: ['Trần Tiểu Long', 'Lý Giai Ân', 'Vương Hạo Nhiên'],
    categories: ['Hoạt hình', 'Phiêu lưu', 'Hài'],
    slug: 'tieu-yeu-quai-nui-lang-lang',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2026-03-10'),
    duration: 118,
    language: ['Tiếng Trung'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://cinema.momocdn.net/img/96739515261817053-tyqnll-compressed.jpg?size=M',
    trailerUrl: 'https://youtu.be/XmpXSsyqPjI',
    videoUrl: 'https://youtu.be/XmpXSsyqPjI',
    tags: ['hoat-hinh', 'fantasy', '2d', 'phieu-luu'],
  },
  {
    code: 'MOV-0017',
    title: 'Bố Già',
    description: 'Phim điện ảnh chuyển thể từ web drama - câu chuyện về người cha già và mối quan hệ cha con.',
    studio: 'Trấn Thành Town',
    director: 'Trấn Thành, Vũ Ngọc Đãng',
    cast: ['Trấn Thành', 'Tuấn Trần', 'Ngân Chi'],
    categories: ['Gia đình', 'Tình cảm', 'Hài'],
    slug: 'bo-gia',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2021-03-12'),
    duration: 128,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://media.vov.vn/sites/default/files/styles/large/public/2021-03/1_114.jpg',
    trailerUrl: 'https://youtu.be/rmPP-DRqEf0?si=Rpa1LS2sxJoUsIFs',
    videoUrl: 'https://youtu.be/oA-BhGNK7qw?si=VNgZL9ONMFyYSpCa',
    tags: ['phim-viet', 'gia-dinh', 'tran-thanh'],
  },
  {
    code: 'MOV-0018',
    title: 'One Punch Man',
    description: 'Saitama là một anh hùng có thể hạ mọi kẻ địch chỉ bằng một cú đấm. Quá mạnh khiến cuộc sống anh trở nên nhàm chán, cho đến khi gặp Genos và gia nhập Hiệp hội Anh hùng, nơi hàng loạt quái vật và tổ chức bí ẩn liên tục xuất hiện.',
    studio: 'Madhouse (Season 1), J.C.Staff (Season 2)',
    director: 'Shingo Natsume (S1), Chikara Sakurai (S2)',
    cast: ['Makoto Furukawa', 'Kaito Ishikawa', 'Aoi Yuki'],
    categories: ['Hành động', 'Hài'],
    slug: 'one-punch-man',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2026-02-27'),
    duration: 176,
    language: ['Tiếng Nhật'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://media.themoviedb.org/t/p/w600_and_h900_face/dT10AxJIXVvRwFAew4tt2RhzJrD.jpg',
    trailerUrl: 'https://youtu.be/eDo_is_Apf4?si=Km1QCDAFgiU4Vp7H',
    videoUrl: 'https://youtu.be/tltUkkvI8yI?si=4v7x8Aa9NyuAwFmu',
    tags: ['onepunchman', 'saitama', 'anime', 'superhero'],
  },
  {
    code: 'MOV-0019',
    title: 'Trạng Tí',
    description: 'Phiêu lưu kỳ thú của cậu bé Tí và những người bạn trong thế giới cổ tích Việt Nam.',
    studio: 'Ngô Thanh Vân Production',
    director: 'Phan Gia Nhật Linh',
    cast: ['Ngô Thanh Vân', 'Trần Ngọc Vàng'],
    categories: ['Phiêu lưu', 'Gia đình', 'Hoạt hình'],
    slug: 'trang-ti',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2026-02-17'),
    duration: 100,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/t/r/trang_ti_relauch_tet_-gui_1_.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=2Mi0CFBghiw',
    videoUrl: 'https://www.youtube.com/watch?v=2Mi0CFBghiw',
    tags: ['phim-viet', 'thieu-nhi'],
  },
  {
    code: 'MOV-0020',
    title: 'Kung Fu Panda 4',
    description: 'Po được chọn làm thủ lĩnh tinh thần mới của Thung lũng Bình Yên, nhưng trước khi nhận vai trò mới, cậu phải đối đầu với mụ tắc kè hoa Chameleon có khả năng sao chép kung fu của các cao thủ. Đồng hành cùng Po là Zhen trong hành trình bảo vệ thành phố Juniper và khám phá ý nghĩa thật sự của việc trở thành chiến binh rồng.',
    studio: 'DreamWorks Animation',
    director: 'Mike Mitchell',
    cast: ['Jack Black', 'Awkwafina', 'Viola Davis', 'Dustin Hoffman', 'Bryan Cranston', 'James Hong', 'Ian McShane', 'Ke Huy Quan'],
    categories: ['Hoạt hình', 'Phiêu lưu', 'Hài'],
    slug: 'tan-bang-phong-than-2',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2026-02-19'),
    duration: 94,
    language: ['Tiếng Anh'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=_inKs4eeHiI',
    videoUrl: 'https://www.youtube.com/watch?v=_inKs4eeHiI',
    tags: ['kungfu-panda', 'dreamworks', 'animation', 'family', 'adventure'],
  },
  {
    code: 'MOV-0021',
    title: 'Thám Tử Lừng Danh Conan: Ngôi Sao 5 Cánh 1 Triệu Đô',
    description: 'Conan cùng Heiji điều tra vụ án liên quan đến thanh kiếm cổ và bí mật gia tộc tại Hakodate. Khi Kaito Kid cũng xuất hiện, cuộc truy đuổi giữa những manh mối lịch sử, bảo vật và âm mưu mới bắt đầu.',
    studio: 'TMS Entertainment',
    director: 'Chika Nagaoka',
    cast: ['Minami Takayama', 'Kappei Yamaguchi', 'Wakana Yamazaki,', 'Rikiya Koyama', 'Yuko Miyamura'],
    categories: ['Hoạt hình', 'Hành động'],
    slug: 'tham-tu-lung-danh-conan-ngoi-sao-5-canh-1-trieu-do',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2024-04-11'),
    duration: 111,
    language: ['Tiếng Nhật'],
    subtitles: ['Tiếng Anh', 'Tiếng Việt'],
    imageUrl: 'https://baodongnai.com.vn/file/e7837c02876411cd0187645a2551379f/082024/conan_20240809221948.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=C4pG3GbhQZw',
    videoUrl: 'https://www.youtube.com/watch?v=C4pG3GbhQZw',
    tags: ['conan', 'detective-conan', 'anime', 'mystery', 'heiji', 'kaito-kid'],
  },
  {
    code: 'MOV-0022',
    title: 'Đất Rừng Phương Nam',
    description: 'Phim kể về cuộc sống gần gũi của Ba, Lúa và Ba Phi trong miền Tây sông nước cùng những câu chuyện về tình bạn, tình yêu và văn hóa con người Nam Bộ Việt Nam.',
    studio: 'Galaxy Studio',
    director: 'Lê Cung Bắc',
    cast: ['NSƯT Thành Lộc', 'Hùng Thuận', 'Phùng Ngọc', 'Mạc Can', 'Việt Anh', 'Hữu Châu'],
    categories: ['Gia đình', 'Phiêu lưu', 'Tình cảm'],
    slug: 'dat-rung-phuong-nam',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2023-12-15'),
    duration: 110,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://baodongnai.com.vn/file/e7837c02876411cd0187645a2551379f/102023/dat_rung_phuong_nam_1_20231013181830.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=Ch0qDq43vJM',
    videoUrl: 'https://www.youtube.com/watch?v=Ch0qDq43vJM',
    tags: ['gia-dinh', 'phim-viet', 'viet-nam', 'at-rung-phuong-nam'],
  },
  {
    code: 'MOV-0023',
    title: 'Doraemon: Nobita Và Bản Giao Hưởng Địa Cầu',
    description: 'Nobita và nhóm bạn bước vào cuộc phiêu lưu âm nhạc để cứu Trái Đất khỏi một thế lực bí ẩn.',
    studio: 'Shin-Ei Animation',
    director: 'Kazuaki Imai',
    cast: ['Wasabi Mizuta', 'Megumi Oohara'],
    categories: ['anime', 'family', 'adventure'],
    slug: 'doraemon-nobita-va-ban-giao-huong-dia-cau',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2024-03-01'),
    duration: 115,
    language: ['Japanese'],
    subtitles: ['Vietnamese', 'English'],
    imageUrl: 'https://baodongnai.com.vn/file/e7837c02876411cd0187645a2551379f/052024/18_2_20240523155958.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=zf0vMnBu1ck',
    videoUrl: 'https://www.youtube.com/watch?v=zf0vMnBu1ck',
    tags: ['doraemon', 'anime', 'family', 'movie-2024'],
  },
  {
    code: 'MOV-0024',
    title: 'Tứ Chiến Trên Không',
    description: '"Tử Chiến Trên Không" là bộ phim hành động – chiến tranh do Galaxy Studio sản xuất, xoay quanh những con người đối mặt với thử thách sinh tử trên bầu trời. Giữa những trận chiến khốc liệt và cảm xúc dâng trào, bộ phim khắc họa tinh thần quả cảm và sự hy sinh vì lý tưởng lớn lao',
    studio: 'Galaxy Studio',
    director: 'Hàm Trần',
    cast: ['Thái Hòa', 'Kaity Nguyễn', 'Trâm Anh', 'Trần Ngọc Vàng', 'Thanh Sơn', 'Võ Điền Gia Huy', 'Đào Duy Bảo Định', 'Ray Nguyễn'],
    categories: ['Hành động', 'Chiến tranh', 'Tâm lý'],
    slug: 'tu-chien-tren-khong',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2026-02-13'),
    duration: 120,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRjWxxfipnqRrQEGWIKdADI4VQfVPo6XeaYX25HEg2isa89mmcc',
    trailerUrl: 'https://www.youtube.com/watch?v=Q-Zf8KhyS6E',
    videoUrl: 'https://www.youtube.com/watch?v=Q-Zf8KhyS6E',
    tags: ['hanh-dong', 'vietnam', 'galaxy', 'khong-chien', 'bom-tan'],
  },
  {
    code: 'MOV-0025',
    title: 'Chú Thuật Hồi Chiến',
    description: 'Yuji Itadori bước vào thế giới chú thuật sau khi nuốt ngón tay của Sukuna và trở thành chú thuật sư để bảo vệ mọi người.',
    studio: 'MAPPA',
    director: 'Sunghoo Park',
    cast: ['Junya Enoki', 'Yuma Uchida', 'Asami Seto', 'Yuichi Nakamura'],
    categories: ['action', 'anime', 'supernatural'],
    slug: 'chu-thuat-hoi-chien',
    status: 'published',
    ageRating: 'T16',
    releaseDate: new Date('2020-10-03'),
    duration: 120,
    language: ['Japanese'],
    subtitles: ['Vietnamese', 'English'],
    imageUrl: 'https://cdn-media.sforum.vn/storage/app/media/thaouyen/nhan-vat-chinh-cua-chu-thuat-hoi-chien-thumbnail.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=cPs3j9LNCjY',
    videoUrl: 'https://www.youtube.com/watch?v=cPs3j9LNCjY',
    tags: ['jujutsu', 'sukuna', 'anime', 'shonen'],
  },
  {
    code: 'MOV-0026',
    title: 'Thanh Gươm Diệt Quỷ: Chuyến Tàu Vô Tận',
    description: 'Tanjiro cùng Nezuko, Zenitsu và Inosuke phối hợp với Viêm Trụ Rengoku điều tra vụ mất tích bí ẩn trên Chuyến Tàu Vô Tận.',
    studio: 'ufotable',
    director: 'Haruo Sotozaki',
    cast: ['Natsuki Hanae, Akari Kito, Hiro Shimono, Yoshitsugu Matsuoka, Satoshi Hino'],
    categories: ['Hành động'],
    slug: 'thanh-guom-diet-quy-chuyen-tau-vo-tan',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2026-02-15'),
    duration: 117,
    language: ['Tiếng Nhật'],
    subtitles: ['Tiếng Việt'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/vi/e/ed/Thanh_G%C6%B0%C6%A1m_Di%E1%BB%87t_Qu%E1%BB%B7_Chuy%E1%BA%BFn_T%C3%A0u_V%C3%B4_T%E1%BA%ADn_Poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=ATJYac_dORw',
    videoUrl: 'https://www.youtube.com/watch?v=ATJYac_dORw',
    tags: ['kimetsu-no-yaiba, thanh-guom-diet-quy, mugen-train, rengoku'],
  },
  {
    code: 'MOV-0027',
    title: 'Shin Cậu Bé Bút Chì: Truyền Thuyết Nhẫn Thuật Ninja',
    description: 'Shinnosuke cùng gia đình Nohara bị cuốn vào một bí mật liên quan đến nhẫn thuật cổ xưa. Cuộc phiêu lưu hài hước nhưng kịch tính bắt đầu khi Shin và những người bạn phải đối đầu thế lực bí ẩn để bảo vệ hòa bình.',
    studio: 'Shin-Ei Animation',
    director: 'Masakazu Hashimoto',
    cast: ['Akiko Yajima', 'Satomi Koorogi', 'Toshiyuki Morikawa', 'Miki Narahashi'],
    categories: ['Hoạt hình', 'Phiêu lưu', 'Hài'],
    slug: 'shin-cau-be-but-chi-truyen-thuyet-nhan-thuat-ninja',
    status: 'published',
    ageRating: 'P',
    releaseDate: new Date('2022-04-21'),
    duration: 100,
    language: ['Tiếng Nhật'],
    subtitles: ['Tiếng Anh', 'Tiếng Việt'],
    imageUrl: 'https://image.tmdb.org/t/p/original/uIOydXZqngqkIs8oLxzkP2eVEPW.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=vOUJrSHHp6g',
    videoUrl: 'https://www.youtube.com/watch?v=vOUJrSHHp6g',
    tags: ['shin', 'anime', 'ninja', 'hoat-hinh', 'gia-dinh'],
  },
  {
    code: 'MOV-0028',
    title: 'Mùa Hè Yêu Dấu Của Chúng Ta',
    description: 'Nhiều năm sau khi chia tay, Choi Ung và Kook Yeon-soo bất ngờ phải gặp lại nhau khi bộ phim tài liệu họ quay thời trung học bỗng nổi tiếng trở lại. Từ những xung đột cũ đến cảm xúc chưa từng nguôi, cả hai dần đối diện với quá khứ và học cách yêu trưởng thành hơn.',
    studio: 'Studio N',
    director: 'Kim Yoon-jin',
    cast: ['Choi Woo-shik', 'Kim Da-mi', 'Kim Sung-cheol', 'Roh Jeong-eui'],
    categories: ['Tình cảm', 'Chính kịch'],
    slug: 'mua-he-yeu-dau-cua-chung-ta',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2021-12-05'),
    duration: 100,
    language: ['Tiếng Hàn'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://www.themoviedb.org/t/p/w1280/bKRocxswBhWwBjM3gvNpL9vfgbz.jpg',
    trailerUrl: 'https://youtu.be/lqU_kT4L0FQ?si=XEkzuVxVafCa_1Tu',
    videoUrl: 'https://youtu.be/lj8TV9q59P4?si=xyD2jtrBKxsvhHdy',
    tags: ['kdrama', 'romance', 'coming-of-age', 'our-beloved-summer'],
  },
  {
    code: 'MOV-0029',
    title: 'Người Thầy Y Đức',
    description: 'Câu chuyện về bác sĩ thiên tài Kim Sa-bu và các bác sĩ trẻ tại bệnh viện Doldam, nơi họ trưởng thành qua những ca cấp cứu sinh tử và bài học y đức sâu sắc.',
    studio: 'SBS Studios',
    director: 'Yoo In-sik & Lee Gil-bok',
    cast: ['Han Suk-kyu', 'Yoo Yeon-seok', 'Seo Hyun-jin', 'Ahn Hyo-seop', 'Lee Sung-kyung'],
    categories: ['Chính kịch', 'Tình cảm'],
    slug: 'nguoi-thay-y-duc',
    status: 'published',
    ageRating: 'T16',
    releaseDate: new Date('2016-11-06'),
    duration: 65,
    language: ['Tiếng Hàn'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://media.themoviedb.org/t/p/w600_and_h900_face/9fbRJgZ2zDTnSUId1bOwsllHNr7.jpg',
    trailerUrl: 'https://youtu.be/4BW040aeQbg?si=soQizy8X0_RFaLjr',
    videoUrl: 'https://youtu.be/BUKKUgxF9Ag?si=Bpk5xZ_Iz_97io8F',
    tags: ['han-quoc', 'y-khoa', 'drama', 'dr-romantic', 'hospital'],
  },
  {
    code: 'MOV-0030',
    title: 'Người Hùng Yếu Đuối',
    description: 'Yeon Si-eun là học sinh top đầu nhưng thể chất yếu. Bằng trí thông minh, tâm lý chiến và sự hỗ trợ của bạn bè, cậu đối đầu với bạo lực học đường để bảo vệ những người mình quan tâm.',
    studio: 'Playlist Studio, Shortcake',
    director: 'Yoo Su-min',
    cast: ['Hong Kyung', 'Shin Seung-ho', 'Park Ji-hoon', 'Choi Hyun-wook'],
    categories: ['Hành động', 'Tâm lý', 'Chính kịch'],
    slug: 'nguoi-hung-yeu-duoi',
    status: 'published',
    ageRating: 'T18',
    releaseDate: new Date('2022-11-17'),
    duration: 40,
    language: ['Tiếng Hàn'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://upload.wikimedia.org/wikipedia/vi/7/7c/Poster_Weak_Hero_Class_1.jpeg',
    trailerUrl: 'https://www.youtube.com/watch?v=6l_t-oL2Mco&list=PLLgg3oeE_irHl4iZViinqkxGEI1BIuWqw',
    videoUrl: 'https://www.youtube.com/watch?v=W2Q40QRG3b8',
    tags: ['han-quoc', 'hoc-duong', 'bao-luc-hoc-duong', 'action', 'weak-hero'],
  },
  {
    code: 'MOV-0031',
    title: 'Hậu cung Như Ý truyện',
    description: 'Từ một mối tình thuở thiếu thời, Như Ý bước vào hậu cung cùng Càn Long. Giữa tranh đấu quyền lực và những âm mưu chốn thâm cung, tình cảm dần rạn vỡ, để lại một câu chuyện bi thương về niềm tin và sự cô độc của bậc mẫu nghi thiên hạ.',
    studio: 'New Classics Media',
    director: 'Wang Jun',
    cast: ['Zhou Xun', 'Wallace Huo'],
    categories: ['Tình cảm'],
    slug: 'hau-cung-nhu-y-truyen',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2018-08-19'),
    duration: 45,
    language: ['Tiếng Trung'],
    subtitles: ['Tiếng Việt'],
    imageUrl: 'https://media.themoviedb.org/t/p/w600_and_h900_face/d6qA9ENvBpic357ogejhfZSmPZh.jpg',
    trailerUrl: 'https://youtu.be/5JsJldjkQQ8?si=60-DIMp_kI4JP3Da',
    videoUrl: 'https://youtu.be/EpYldAVlcg8?si=UtHNz1m2MsBP0s0n',
    tags: ['cung đấu', 'cổ trang', 'hậu cung', 'Trung Quốc', 'bi kịch'],
  },
  {
    code: 'MOV-0032',
    title: 'Doctor Slump',
    description: 'Hai "thiên tài" từng là đối thủ thời đi học gặp lại nhau khi cả hai đang chạm đáy sự nghiệp và tinh thần. Từ cạnh tranh, họ dần chữa lành cho nhau và tìm lại ý nghĩa cuộc sống.',
    studio: 'SLL; HighZium Studio',
    director: 'Oh Hyun-jong',
    cast: ['Park Hyung-sik', 'Park Shin-hye', 'Yoon Park', 'Gong Seong-ha'],
    categories: ['Y khoa', 'Lãng mạn', 'Hài'],
    slug: 'doctor-slump',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2024-01-26'),
    duration: 60,
    language: ['Tiếng Hàn'],
    subtitles: ['Tiếng Việt'],
    imageUrl: 'https://media.themoviedb.org/t/p/w600_and_h900_face/iOWmbZEbhvrYyWm6O4W3oHf2S9B.jpg',
    trailerUrl: 'https://youtu.be/ABcIUcy6RmA?si=QaA3v0xuMBbvSp5Z',
    videoUrl: 'https://youtu.be/29c-l9CPHL4?si=khZxhIAVQW0eeZjO',
    tags: ['y khoa', 'tình cảm', 'Hàn Quốc', 'hài lãng mạn'],
  },
  {
    code: 'MOV-0033',
    title: 'Người vợ cuối cùng',
    description: 'Phim cổ trang – tâm lý lấy bối cảnh Việt Nam xưa, xoay quanh thân phận một người vợ lẽ và bi kịch tình cảm, danh phận trong xã hội phong kiến.',
    studio: ' 1111 Films, LotteTFilm, Anh Tuan Production',
    director: 'Victor Vũ',
    cast: ['Kaity Nguyễn', 'Thuận Nguyễn', 'Quang Thắng'],
    categories: ['Tâm lý', 'Cổ trang'],
    slug: 'nguoi-vo-cuoi-cung',
    status: 'published',
    ageRating: 'T18',
    releaseDate: new Date('2023-11-02'),
    duration: 132,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://media.themoviedb.org/t/p/w188_and_h282_face/tNoRpzsrOOFISEtXbllD0RgfzVt.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=JcJ-wemgVbQ',
    videoUrl: 'https://youtu.be/05Q7O7MH1Cg?si=6Jfn0jGNpO4E3i9W',
    tags: ['cổ trang Việt', 'tâm lý', 'tình cảm ', ' bi kịch'],
  },
  {
    code: 'MOV-0034',
    title: 'Frieren – Pháp sư tiễn táng',
    description: 'Sau khi tổ đội anh hùng đánh bại Ma Vương, nữ pháp sư elf Frieren bắt đầu hành trình mới để hiểu con người và ý nghĩa của ký ức, chia ly.',
    studio: 'Madhouse',
    director: 'Saitō Keiichirō',
    cast: [],
    categories: ['Phiêu lưu', 'Fantasy', 'Drama'],
    slug: 'frieren-phap-su-tien-tang',
    status: 'published',
    ageRating: 'T13',
    releaseDate: new Date('2023-09-28'),
    duration: 24,
    language: ['Tiếng Nhật'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://media.themoviedb.org/t/p/w600_and_h900_face/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
    trailerUrl: 'https://youtu.be/y2q2I1PG8Zs?si=Th8O57vEmtRakIVJ',
    videoUrl: 'https://youtu.be/kSn_bSgJaH4?si=ctmNIAWyfhu_2aaD',
    tags: ['anime', 'fantasy', 'phiêu lưu', ' chữa lành', 'phép thuật'],
  },
  {
    code: 'MOV-0035',
    title: 'Mưa Đỏ',
    description: '"Mưa Đỏ" là bộ phim Việt Nam khai thác câu chuyện tình yêu và số phận con người giữa những biến cố dữ dội. Phim mang màu sắc tâm lý – cảm xúc, với nhiều phân cảnh cao trào và đậm chất điện ảnh.',
    studio: ' Điện ảnh Quân đội Nhân dân ',
    director: 'Thượng tá, NSƯT Đặng Thái Huyền',
    cast: ['Lê Hạ Anh', 'Steven Nguyễn', 'Hòa Minzy', 'Lê Thanh Nhã'],
    categories: ['Tâm lý', 'Tình cảm'],
    slug: 'mua-do',
    status: 'published',
    ageRating: 'T16',
    releaseDate: new Date('2024-11-28'),
    duration: 123,
    language: ['Tiếng Việt'],
    subtitles: ['Tiếng Anh'],
    imageUrl: 'https://media.themoviedb.org/t/p/w600_and_h900_face/iQDXzA9r19VYmCACxKJphMS2ijS.jpg',
    trailerUrl: 'https://youtu.be/UEqjUBGjvwI?si=0YIQ2E4oTN4WfVwz',
    videoUrl: 'https://www.youtube.com/watch?v=I7tfl_7Ho0M',
    tags: ['phim-viet', 'tinh-cam', 'tam-ly'],
  },
  {
    code: 'MOV-0037',
    title: 'Jujutsu Kaisen: Gojo vs Sukuna',
    description: 'Trận chiến định mệnh giữa Satoru Gojo – chú thuật sư mạnh nhất – và Ryomen Sukuna, vua nguyền hồn, trong arc Shinjuku của Jujutsu Kaisen. Cuộc đối đầu đỉnh cao với những màn thi triển Lãnh Địa (Domain Expansion) nghẹt thở, kỹ xảo mãn nhãn và chiến thuật cực kỳ căng thẳng.',
    studio: 'MAPPA Studio',
    director: 'Shota Goshozono',
    cast: ['Yuichi Nakamura', 'Junichi Suwabe'],
    categories: ['Hành động', 'Phiêu lưu', 'Anime'],
    slug: 'jujutsu-kaisen-gojo-vs-sukuna',
    status: 'published',
    ageRating: 'T16',
    releaseDate: new Date('2026-02-25'),
    duration: 135,
    language: ['Tiếng Nhật'],
    subtitles: ['Tiếng Việt', 'Tiếng Anh'],
    imageUrl: 'https://iweather.edu.vn/upload/2025/03/su-gojo-2.webp',
    trailerUrl: 'https://youtu.be/H0wAYuofaeM?si=6N89vXEFw9Dmbzcp',
    videoUrl: 'https://youtu.be/XFRJd0F7x4Y?si=AUJwAG2q6r57eyye',
    tags: ['sukuna', 'gojo', 'jujutsu kaisen'],
  },
];

async function main() {
  console.log(`[seed] Clearing old movies...`);
  await prisma.movie.deleteMany({});
  
  console.log(`[seed] Creating ${movies.length} movies...`);
  for (const movie of movies) {
    await prisma.movie.create({ data: movie });
    console.log(`  [created] ${movie.code} - ${movie.title}`);
  }
  console.log(`[seed] Done! Created ${movies.length} movies.`);
}

main()
  .catch((e) => {
    console.error('[seed] Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
